server:
  port: 8082
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://120.78.172.84:3306/zkdb
    username: root
    password: mojay0118
  cloud:
    refresh:
      refreshable: none
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 120.78.172.84:22122
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.leyou.item.domain