server:
  port: 10010
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://120.78.172.84:3306/zkdb
    username: root
    password: mojay0114
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}