package com.leyou.item.mapper;

import com.leyou.item.domain.Order;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated Fri Aug 02 16:38:41 CST 2019
     */
    long countByExample(Order example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated Fri Aug 02 16:38:41 CST 2019
     */
    int deleteByExample(Order example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated Fri Aug 02 16:38:41 CST 2019
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated Fri Aug 02 16:38:41 CST 2019
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated Fri Aug 02 16:38:41 CST 2019
     */
    List<Order> selectByExample(Order example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated Fri Aug 02 16:38:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") Order example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated Fri Aug 02 16:38:41 CST 2019
     */
    int updateByExample(@Param("record") Order record, @Param("example") Order example);
}